concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: inputs.jdk-version == 11
      name: Set up JDK ${{ inputs.jdk-distribution }} 17 to build for JDK 11 test
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ inputs.jdk-distribution }}
        java-version: 17
    - continue-on-error: true
      if: inputs.jdk-version == 11
      name: Build with Maven and JDK 17 for JDK 11 Tests
      run: mvn -U -B -ntp clean install ${{ inputs.args }} -DskipTests
    - continue-on-error: true
      name: Set up JDK ${{ inputs.jdk-distribution }} ${{ inputs.jdk-version }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ inputs.jdk-distribution }}
        java-version: ${{ inputs.jdk-version }}
    - continue-on-error: true
      if: inputs.jdk-version == 11
      name: Test with Maven and JDK 11 with -DnoCompile
      run: mvn -U -B -ntp test -DnoCompile ${{ inputs.args }} -rf testsuite
    - continue-on-error: true
      if: inputs.jdk-version != 11
      name: Build and test with Maven
      run: mvn -U -B -ntp clean install ${{ inputs.args }}
    strategy:
      fail-fast: false
    timeout-minutes: ${{ fromJSON(inputs.timeout) }}
name: Manual Build and Test
on:
  repository_dispatch:
    types: trigger-ga___build-manual.yml
