env:
  CHANGE_MENTIONS: '@wildfly/prod'
  DEPS_CHANGED_LABEL_NAME: deps-changed
  DEPS_OK_LABEL_NAME: deps-ok
jobs:
  compare:
    if: '${{ github.event.workflow_run.event == ''pull_request'' && github.event.workflow_run.conclusion
      == ''success'' }}

      '
    permissions:
      actions: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifacts
      uses: actions/github-script@v7.0.1
      with:
        script: "var artifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nconsole.log(artifacts);\nvar\
          \ matchArtifact = artifacts.data.artifacts.filter((artifact) => {\n  return\
          \ artifact.name == \"input-artifacts\"\n})[0];\nvar download = await github.rest.actions.downloadArtifact({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   artifact_id:\
          \ matchArtifact.id,\n   archive_format: 'zip',\n});\nvar fs = require('fs');\n\
          fs.writeFileSync('${{github.workspace}}/input.zip', Buffer.from(download.data));\n"
    - continue-on-error: true
      id: prepare
      name: Set needed env vars in outputs
      run: 'unzip input.zip

        echo current directory contents

        ls -al

        echo "deps_ok_label_name=${DEPS_OK_LABEL_NAME}" >> $GITHUB_OUTPUT

        echo "deps_changed_label_name=${DEPS_CHANGED_LABEL_NAME}" >> $GITHUB_OUTPUT

        echo "change_mentions=${CHANGE_MENTIONS}" >> $GITHUB_OUTPUT


        echo Reading PR number

        tmp=$(<pr)

        echo "PR: ${tmp}"

        echo "pr=${tmp}" >> $GITHUB_OUTPUT


        echo Reading base version files

        tmp=$(<baseVersions)

        echo "Base version files: ${tmp}"

        echo "base_files=${tmp}" >> $GITHUB_OUTPUT


        echo Reading new version files

        tmp=$(<newVersions)

        echo "New version files: ${tmp}"

        echo "new_files=${tmp}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Check versions
      uses: wildfly/dep-tree-diff@master
      with:
        base-version-files: ${{ steps.prepare.outputs.base_files }}
        deps-changed-label: ${{ steps.prepare.outputs.deps_changed_label_name }}
        deps-ok-label: ${{ steps.prepare.outputs.deps_ok_label_name }}
        new-version-files: ${{ steps.prepare.outputs.new_files }}
        pr: ${{ steps.prepare.outputs.pr }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tool-change-mentions: ${{ steps.prepare.outputs.change_mentions }}
name: Dependency Tree Reporter
on:
  repository_dispatch:
    types: trigger-ga___dep-diff-workflow_run.yml
permissions: {}
