concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
jobs:
  wildfly-jre-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: setup-java
      name: Setup JRE ${{ matrix.java }} for building
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-package: jre
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: jre-home
      name: Set the JRE Home
      run: 'echo "JRE_HOME=$JAVA_HOME" >> "$GITHUB_OUTPUT"

        '
    - continue-on-error: true
      name: Setup JDK ${{ matrix.java }} for building
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build and verify WildFly with JRE ${{ matrix.java }}
      run: 'mvn -B clean install -DskipTests -Denforcer.skip=true -Dcheckstyle.skip=true

        cd testsuite

        echo "Running: mvn -B verify -Dcontainer.java.home=${{ steps.jre-home.outputs.JRE_HOME
        }} -fae"

        mvn -B verify -DnoCompile -Dcontainer.java.home=${{ steps.jre-home.outputs.JRE_HOME
        }} -fae

        '
    - continue-on-error: true
      if: failure()
      name: Upload Surefire Reports on Failure
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-${{ matrix.java }}
        path: '**/surefire-reports/'
    - continue-on-error: true
      if: failure()
      name: Upload Server Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: server-logs-${{ matrix.java }}
        path: '**/server.log'
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        - '17'
        - '21'
name: WildFly JRE build
on:
  repository_dispatch:
    types: trigger-ga___jdk-jre-build.yml
