jobs:
  wildfly-build:
    outputs:
      wildfly-version: ${{ steps.version.outputs.wildfly-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout WildFly
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.git-log-number }}
        ref: ${{ inputs.wildfly-branch }}
        repository: ${{ inputs.wildfly-repo }}
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Show Git commit logs
      run: git log -n ${{ inputs.git-log-number }}
    - continue-on-error: true
      name: Build WildFly
      run: mvn -B clean install -DskipTests -Dcheckstyle.skip=true -Denforcer.skip=true
    - continue-on-error: true
      id: version
      run: echo "wildfly-version=$(mvn -B help:evaluate -Dexpression=project.version
        -DforceStdout -q)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      name: Archive the repository
      run: 'cd ~

        find ./.m2/repository -type d -name "*SNAPSHOT" -print0 | xargs -0 tar -czf
        ~/wildfly-maven-repository.tar.gz

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: wildfly-maven-repository
        path: ~/wildfly-maven-repository.tar.gz
        retention-days: 5
name: Build WildFly Upstream
on:
  repository_dispatch:
    types: trigger-ga___shared-wildfly-build.yml
