jobs:
  wildfly-build-and-test:
    name: ${{ matrix.os }}-jdk${{ matrix.java }} ${{ inputs.test-arguments }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: wildfly/wildfly
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.maven-repo-name }}
        path: .
    - continue-on-error: true
      name: Extract Maven Repo
      run: 'tar -xzf ${{ inputs.maven-repo-path }} -C ~

        '
      shell: bash
    - continue-on-error: true
      if: matrix.java == 11
      name: Set up JDK 17 and JDK 11 for JDK11 execution
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17

          11

          '
    - continue-on-error: true
      if: matrix.java != 11
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: matrix.java == 11
      name: Build WildFly SNAPSHOT ${{ inputs.build-arguments }}  ${{ inputs.test-arguments
        }} with JDK 17 for JDK 11 tests
      run: JAVA_HOME=$JAVA_HOME_17_${{ runner.arch }} mvn -U -B -ntp clean install
        ${{ inputs.build-arguments }} ${{ inputs.test-arguments }} -DskipTests
      shell: bash
    - continue-on-error: true
      if: matrix.java == 11
      name: Test WildFly SNAPSHOT ${{ inputs.build-arguments }}  ${{ inputs.test-arguments
        }} with -DnoCompile for JDK 11 tests
      run: JAVA_HOME=$JAVA_HOME_${{ matrix.java }}_${{ runner.arch }} mvn -U -B -ntp
        test -DnoCompile ${{ inputs.build-arguments }} ${{ inputs.test-arguments }}
        -rf testsuite
      shell: bash
    - continue-on-error: true
      if: matrix.java != 11
      name: Build and Test WildFly SNAPSHOT ${{ inputs.build-arguments }}  ${{ inputs.test-arguments
        }}
      run: JAVA_HOME=$JAVA_HOME_${{ matrix.java }}_${{ runner.arch }} mvn -U -B -ntp
        clean install ${{ inputs.build-arguments }} ${{ inputs.test-arguments }}
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Find reports
      run: "{\n  echo 'SUREFIRE_REPORTS<<EOF'\n  find . -path '**/surefire-reports/*.xml'\n\
        \  echo EOF\n} >> \"$GITHUB_ENV\"\n"
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Find server logs
      run: "{\n  echo 'SERVER_LOGS<<EOF'\n  find . -path '**/server.log'\n  echo EOF\n\
        } >> \"$GITHUB_ENV\"\n"
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Test Reports on Failure
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
        path: ${{ env.SUREFIRE_REPORTS }}
    - continue-on-error: true
      if: failure()
      name: Upload Server Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: server-logs-${{ matrix.os }}-${{ matrix.java }}
        path: ${{ env.SERVER_LOGS }}
    strategy:
      fail-fast: false
      matrix:
        java: ${{ fromJson(inputs.java-versions) }}
        os: ${{ fromJson(inputs.os) }}
name: Build and Test WildFly
on:
  repository_dispatch:
    types: trigger-ga___shared-wildfly-build-and-test.yml
